# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
