# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20170118_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='image',
            field=models.ImageField(null=True, upload_to='bill_images/'),
        ),
    ]
