# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20170118_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='image',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
